on:
  push:
    tags:
      - '*-staging*'

name: Deploy on Now (Staging)
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: release
      uses: msurguy/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: "--local-config=./staging.now.json"
    - name: alias
      uses: msurguy/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: "alias -A ./staging.now.json"
